Use [SistemaDispensario]

CREATE TABLE dbo.Tags
	(
	Id bigint NOT NULL IDENTITY (1, 1),
	Nombre varchar(50) NOT NULL,
	Icono varchar(5) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Tags ADD CONSTRAINT
	PK_Table_1 PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Tags SET (LOCK_ESCALATION = TABLE)
GO